### ISSUE TITLE
Question about match-v5

### ISSUE THREAD

**Issue by Lucasnl** [dolejska-daniel/riot-api#102]
Hey I really enjoy your work and i want to know if you will  update the match V4 to V5 ?

https://twitter.com/RiotGamesDevRel/status/1382471243744518145

Thanks !

**Comment by dolejska-daniel** [comment]
Hello! I'm happy to hear that you enjoy the library. I'll soon take a look at updating the endpoints.

**Comment by Lucasnl** [comment]
Thanks you're the best !!
