### ISSUE TITLE
Question about Winrate per Champion

### ISSUE THREAD

**Issue by New-on-Git** [dolejska-daniel/riot-api#103]
Hello,

I'm wondering if there's any solutions of getting the winrate per champion easily.

I'm actually getting it by using $api->getMatchlistByAccount then $api->getMatch to have the infos about who's winning each game and then comparing if the player is in the same team as the winning team.
But at the end it's making me doing a lot of API call ( one for each game). It also makes my page really slow to load.
Any idee on how to make it less heavy or if there's another better option for this ? 

Also, because of my Developement API Key i'm able to do only  the last 100 game. Is this the limit for this ?

**Comment by dolejska-daniel** [comment]
These limitations are intended, and as far as I know, there is no better way to acquire such statistics.

**Comment by New-on-Git** [comment]
ok ! Thanks a lot
