### ISSUE TITLE
I have one probleme please autoload.php

### ISSUE THREAD

**Issue by hakushakusama** [dolejska-daniel/riot-api#11]
How i am supposed too create one  autoload.php  
since i am a begginer on php

**Comment by dolejska-daniel** [comment]
Hello,

in this case, best thing you can probably do is to install [Composer](https://getcomposer.org/download/) and let it handle autoloading for you. If you don't know your way around it, please check out [this website](https://www.codementor.io/jadjoubran/php-tutorial-getting-started-with-composer-8sbn6fb6t) hope it helps.

Basically all you need to do is to install it, in your project directory create `composer.json` and fill it with and call one command:
```
{
    "require": {
        "dolejska-daniel/riot-api": "^1.0.0",
    }
}
```

It gets quite tricky when selecting a version to download.. You can check versions of this library at [Packagist.org](https://packagist.org/packages/dolejska-daniel/riot-api) and read something about how versions work in composer [here](https://getcomposer.org/doc/articles/versions.md).

Then, open command line in the directory where you've created the file and type `composer install`. This will create `vendor` directory, automatically install all the required things and in that directory it will create `autoload.php`, which you will only include in your PHP files.

If you won't manage to succeed please check out some YouTube videos, there is plenty of people describing how to work with Composer.

Good luck,
Daniel

**Comment by hakushakusama** [comment]
what about if i want to install it   on  my  hoster, but taking the fact that my web host is free so i can't install things like composer

**Comment by dolejska-daniel** [comment]
It is not necessary to install it on the webserver.. Just install it on your computer, download required packages and then upload to the webserver.
