### ISSUE TITLE
CurrentGameParticipant is not up to date

### ISSUE THREAD

**Issue by DomBra** [dolejska-daniel/riot-api#13]
The class `\RiotAPI\Objects\CurrentGameParticipant` changed around patch `7.24.1`, and since there was no release yet, I am creating this issue. 

 * `teamId` -> no change required
 * `spell1Id` -> no change required
 * `spell2Id` -> no change required
 * `championId` -> no change required
 * `profileIconId` -> no change required
 * `summonerName` -> no change required
 * `bot` -> no change required
 * `summonerId` -> no change required
 * `perks` -> is an array that has `perkIds = array()`, `perkStyle = int`, `perkSubStyle = int`
 * `runes` -> should be removed
 * `masteries` -> should be removed

If I have time I might open a new PR.

**Comment by dolejska-daniel** [comment]
Hello,

yeah - that is correct, some of the changes are already in **v2.0.0-rc.1** 1e26614. I am going to mine latest changes to the objects from their API documentation ASAP, thanks for noticing.

**Comment by DomBra** [comment]
Is there any information regarding when this PR will be merged? Is there anything left; if yes what?

**Comment by dolejska-daniel** [comment]
Latest changes are in **v2.0.0-rc.2** a16a6e2. There shouldn't be anything missing actually..

**Comment by DomBra** [comment]
As far as I see only tests are missing right?

**Comment by dolejska-daniel** [comment]
@DomBra yes, that's true.
