### ISSUE TITLE
SET_TOURNAMENT_KEY on Wiki

### ISSUE THREAD

**Issue by regiszanandrea** [dolejska-daniel/riot-api#14]
Hi @dolejska-daniel,

I didn't find anything on Wiki that we have to use _RiotAPI::SET_TOURNAMENT_KEY_ to use Tournament's API. I passed hours debugging the package to discovery that I have to use the SET_TOURNAMENT_KEY.

So, please, can you add something on Wiki to help others here: [https://github.com/dolejska-daniel/riot-api/wiki/LeagueAPI:-Resources-and-endpoints#tournament---tournament-stub-](url), please?

Thank you.

**Comment by dolejska-daniel** [comment]
Hello, @regiszanandrea!

I am sorry that it was not described anywhere, I will fix that immediately. Thank you for the idea! 😄
