### ISSUE TITLE
Undefined offset: -1

### ISSUE THREAD

**Issue by angelkurten** [dolejska-daniel/riot-api#17]
```php
$games = $this->parseCollection($this->getMatchlistByAccount($user, [440, 420], null, null, null, null, null, $total)->matches);
        $details = new Collection();
        $games->each(function ($game) use ($details) {
            $details->push(
                $this->getMatch($game->gameId)
            );
        });

        return $details;
```

RESULT:

ErrorException (E_NOTICE)
Undefined offset: -1

**Comment by dolejska-daniel** [comment]
Hello,

are you sure that it is a problem on side of the library? You are using a lot of own functions which I don't know, also the PHP error should tell you in which file and on which line the error occurred, could you show me?

**Comment by angelkurten** [comment]
Code: [https://github.com/angelkurten/TrackerLOL/blob/master/app/Http/Controllers/UserController.php](url)

LOLApi: [https://github.com/angelkurten/TrackerLOL/blob/master/app/Riot/LOL.php](url)

![image](https://user-images.githubusercontent.com/2807174/41757305-e3ae9338-75a6-11e8-9010-13c626340df3.png)

**Comment by dolejska-daniel** [comment]
Hi again,

could you provide me with raw RiotAPI response? Value `-1` is very suspicious in this scenario.

The library is trying to link static champion data to the response, but its looking for champion with id `-1`, which of course does not exist. Question is, how did `-1` get to the response data.

**Comment by angelkurten** [comment]
Solution: 
![image](https://user-images.githubusercontent.com/2807174/41763040-7e551068-75c2-11e8-82ad-cee3bb16c67f.png)

**Comment by dolejska-daniel** [comment]
Well, yeah, but that doesn't solve the problem itself. Could you find the raw data from the API for me?
