### ISSUE TITLE
Add an option to export current api usage statistics

### ISSUE THREAD

**Issue by cohenu** [dolejska-daniel/riot-api#18]
Hi,
I wanted to know if it's possible to export the current usage statistics (Rate Limit Tokens) so that I can export them to prometheus.
Is there a build in function for fetching the current usage statistics?

**Comment by TheKeymaster** [comment]
I am not sure about exporting but you can atleast see this data at the developers website by Riot Games. You can filter by API Keys and other details such as specific methods etc.
For me it looks like:
![image](https://user-images.githubusercontent.com/20555112/43205369-7e7966c2-9023-11e8-8714-d5ad298413d1.png)

**Comment by TheKeymaster** [comment]
They also provide some really cool graphs that I just saw 📈 

![image](https://user-images.githubusercontent.com/20555112/43205673-301cfbd2-9024-11e8-9eb3-f1dc22f9604e.png)

**Comment by cohenu** [comment]
@TheKeymaster nice, where I can find the graphs ?

**Comment by TheKeymaster** [comment]
Sorry for my late answer. You can find them under https://developer.riotgames.com/. At the bottom there is a gray button that says "View API Key usage".

**Comment by TheKeymaster** [comment]
I hope this screenshot explains enough :)
![riotgames_api](https://user-images.githubusercontent.com/20555112/43354908-fdb9145a-9253-11e8-9513-50d271171b1d.png)

**Comment by cohenu** [comment]
@TheKeymaster I found already the api key usage per endpoint but I cannot find the graphs - is it in the same portal?

**Comment by dolejska-daniel** [comment]
Since this is not really a bug or feature of this library and it has been inactive for quite some time, I will close this issue.
