### ISSUE TITLE
Support for RiotApi v4

### ISSUE THREAD

**Issue by regiszanandrea** [dolejska-daniel/riot-api#24]
**Is your feature request related to a problem? Please describe.**
The Riot Developers announced that v3 API will be deprecated soon. 

**Describe the solution you'd like**
Today, they made available the endpoints from the new API version, v4. In the link below, there are the endpoints that needed to be implemented:

https://developer.riotgames.com/api-methods/

**Comment by boraguler** [comment]
I'm waiting for it too, can help you with it Daniel if needed.

**Comment by dolejska-daniel** [comment]
Hi guys,

there will be only minor adjustments to match `v4` endpoint call changes. Thought there would be things I'd be grateful to get helped with -- I'll let you know soon 😆.

**Comment by dolejska-daniel** [comment]
So... I know that noone likes to **write tests** (#26 ) - BUT it needs to be done. And if you could help, that would be awesome!

There are also some things to be done to **bridge StaticData calls from RiotAPI to DataDragonAPI** (#25). But these are not that important.

**Comment by dolejska-daniel** [comment]
In the end, I wll manage to fix the tests by myself.

#25 should be priority now.

**Comment by dolejska-daniel** [comment]
@regiszanandrea, @boraguler library should support `v4` endpoints now! Please test it 😸. Note that Champion Mastery endpoint is not working correctly yet (Serivce unavailable).

Also, the tests should be kind of working again. But definitely are **not complete**. So any additions are welcome.

**Comment by regiszanandrea** [comment]
@dolejska-daniel Working as Designed.

Thank you so much ❤️

**Comment by regiszanandrea** [comment]
Hey @dolejska-daniel, I'll create a new issue for Tournament V4 Support, it's ok?

**Comment by dolejska-daniel** [comment]
@regiszanandrea sure is! Didn't hear anything about Tournament v4 😮

**Comment by regiszanandrea** [comment]
@dolejska-daniel I think the only thing that will change is in the tournament code creation, passing the encrypted summonerId

**Comment by dolejska-daniel** [comment]
Hey guys! `Champion Mastery v4` and `Tournament Stub v4` are up and running on a58847ca04b3a4e31ee6a036046f1608fe4dfeed 😼.

**Comment by regiszanandrea** [comment]
@dolejska-daniel Tournament v4 is available :)

**Comment by dolejska-daniel** [comment]
All `v4` endpoints should be working on [`v3.0.0-alpha`](https://github.com/dolejska-daniel/riot-api/releases/tag/v3.0.0-alpha). Static data through RiotAPI still not implemented.

**Comment by regiszanandrea** [comment]
@dolejska-daniel Love you  ❤️
