### ISSUE TITLE
Plans for RiotApi v4

### ISSUE THREAD

**Issue by TheKeymaster** [dolejska-daniel/riot-api#27]
Hi @dolejska-daniel ,

do you already have plans on implementing the new [`v4` Riot API](https://developer.riotgames.com/api-methods/) ? Since I use your library on a daily basis it would be great to see if it still was compatible with the new coming version for the API.
Thanks for your great work!

**Comment by TheKeymaster** [comment]
Ok I will close this issue since you are already working on it! Love your work! Thanks!

**Comment by dolejska-daniel** [comment]
Hey @TheKeymaster! Everything is actually already implemented (except Tournaments `v4`) and should be working (last time i checked Champion Mastery was not working on the API side). You can read more about it in #24. I'll try to make a new release as soon as everything gets verified by tests and Travis stops showing build as failing.

Also - huge thanks for the support :smiley_cat:. If you'd have any improvement ideas on your mind, feel free to share with us by creating [feature request issue](https://github.com/dolejska-daniel/riot-api/issues/new?template=Feature_request.md) or if you'd like to implement it send PRs!
