### ISSUE TITLE
curious about Rate LIMIT.

### ISSUE THREAD

**Issue by merons** [dolejska-daniel/riot-api#29]
Currently, we are making good use of this api.
However, I want to use multiple API keys because of limitations of API use.
So I checked the cache in the cache folder and it seems that each key has its own cache. 
If I try to use multiple API keys, will LIMIT work well with each change in key value?

**Comment by dolejska-daniel** [comment]
Hello and thank you for your interest in this library!

[Rate limiting control](https://github.com/dolejska-daniel/riot-api/blob/a58847ca04b3a4e31ee6a036046f1608fe4dfeed/src/RiotAPI/Definitions/RateLimitStorage.php#L172) is built to work with multiple API keys by default. There will be no problem using it this way. You can also change the API key during lifetime of the library just by using [`$api->setSetting(RiotAPI::SET_API_KEY, THE_KEY);`](https://github.com/dolejska-daniel/riot-api/blob/a58847ca04b3a4e31ee6a036046f1608fe4dfeed/src/RiotAPI/RiotAPI.php#L714), if you'd need that.
