### ISSUE TITLE
Error on getMatchlistByAccount and createTournamentCodes and createTournamentCodes_STUB

### ISSUE THREAD

**Issue by kvacquier** [dolejska-daniel/riot-api#36]
**Describe the bug**
Cant do the request properly

**To Reproduce**
use the functions with arguments

Solution: 
Add a '?' at the end of the setressource argument string exemple "setResource(self::RESOURCE_MATCH, "/matchlists/by-account/%i?")"

**Comment by dolejska-daniel** [comment]
Hello, what is the actual error you're getting? This description doesn't provide any useful information and the "solution" doesn't seem really related.

**Comment by regiszanandrea** [comment]
Hi @dolejska-daniel, I'm still getting error 500 on createTournamentCodes function using 3.0.1 version, any thoughts if is RIOT or the library?
