### ISSUE TITLE
Wiki typo/bug

### ISSUE THREAD

**Issue by tiptone** [dolejska-daniel/riot-api#39]
In the wiki, on the LeagueAPI::StaticData endpoints page, the example code doesn't work.

1. Go to Wiki -> LeagueAPI::StaticData endpoints page
2. Settings table shows "LeagueAPI::"
3. Code blocks show "RiotAPI::"
4. Example code doesn't work

Update the code blocks to use "LeagueAPI::" instead of "RiotAPI::" and the code works perfectly.

**Comment by dolejska-daniel** [comment]
Thanks for letting me know @tiptone! Fixed now.
