### ISSUE TITLE
getMatchlistByAccount Doesn't accept arrays for queue and season

### ISSUE THREAD

**Issue by cohenu** [dolejska-daniel/riot-api#41]
**Describe the bug**
Ever since v3.0.2 `getMatchlistByAccount` doesn't accept arrays when the documentation lists the fields as `int|array`.
The fields are:
- `$queue`
- `$season`
- `$champion`

The method returns the following error:
```html
 LeagueAPI: Request is invalid. Bad request - Query parameter 'season' must be numeric
```
The match list endpoint should be able to retrieve data for multiple queues/seasons/champions.

**To Reproduce**
1. Initialize an instance of `LeagueAPI`
2. Make a requests using `getMatchlistByAccount` and set one of the affected fields as an array of integers

**Expected behavior**
Should return a match list with the supplied filters applied.

**Screenshots**
Not relevant

**Server (please complete the following information):**
 - PHP version: 7.2.13

**Additional context**
Seems like a constraint was placed on the fields and it no longer accepts arrays.

**Comment by dolejska-daniel** [comment]
As per [API Documentation](https://developer.riotgames.com/api-methods/#match-v4/GET_getMatchlist), arrays (`Set[int]`) should be supported by API endpoint. I'll contact API guys about that.

**Comment by dolejska-daniel** [comment]
So there was a problem when building URL query parameters, the parameters are accepted in kind of non-standard way on the API. Should be fixed now.

**Comment by cohenu** [comment]
@dolejska-daniel Hey, i noticed the fix was pushed to master but a new version wasn't pushed to composer.

**Comment by dolejska-daniel** [comment]
Whoops, forgot! Fixed 😸.
