### ISSUE TITLE
Access var in LeagueItemDto

### ISSUE THREAD

**Issue by maxiz22** [dolejska-daniel/riot-api#42]
**Describe the bug**
Access var in LeagueItemDto class. Please change $summonerId and $summonerName to public 
in Riot-Api v3
namespace RiotAPI\LeagueAPI\Objects;
class LeagueItemDto extends ApiObject {
    /** @var string $summonerId */
    public $summonerId;

    /** @var string $summonerName */
    public $summonerName;
}

I offer myself as a contributor for this proyect , it's genial
Regards!

**Comment by dolejska-daniel** [comment]
Hello and thanks for the report @maxiz22!
The object properties are not yet in the [official API docs](https://developer.riotgames.com/api-methods/#league-v4/GET_getLeagueById), so it wasn't updated as it should have been when I processed the documentation.
