### ISSUE TITLE
Getting champion name by champion ID for DDDragon

### ISSUE THREAD

**Issue by Lagily** [dolejska-daniel/riot-api#46]
Hey quick question about the DDragon functions

I have gotten myself a MatchDTO using your library and am trying to show the champion icons, however now I only have a champion ID from the bans (as an example). How do I go about finding the champion name the best way?

Something like this but be really nice, but doesn't work as it seems to only take the champion_name and not the champion_id

`DataDragonAPI::getChampionIcon($match->teams[1]->bans[0]->championId)`

Any ideas?

**Comment by dolejska-daniel** [comment]
Hey,

if you enable `LeagueAPI::SET_STATICDATA_LINKING` before the call, you should be able to use this:

```php
DataDragonAPI::getChampionIconO($match->teams[1]->bans[0]->staticData);
```

**Comment by Lagily** [comment]
That's really cool thank you!

**Comment by Lagily** [comment]
Would this also work on ParticipantDTO? There is a championId in there!

**Comment by Lagily** [comment]
works perfectly, thank you for your help

**Comment by Lagily** [comment]
Sorry, another question, I am using the /match Endpoint to get a match using getMatch(), everything seems to be filled but the ParticipantIdentityDTO player fields are all null, is this perhaps a bug?

**Comment by Lagily** [comment]
Sorry I do need to bother you again, what do I do about for example:

ParticipantDTO::$spell1id

How do I go on about getting the icon for that?

**Comment by dolejska-daniel** [comment]
I think that you will currently have to use some other functions to get the key from the ID first. Like so:

```php
$league_api = new LeagueAPI([...]);
// ...
$id = $participant->spell1id;
$spell_icon = $league_api->getStaticSummonerSpellById($id);
echo DataDragonAPI::getSummonerSpellIconO($spell_icon);
```

**Comment by Lagily** [comment]
really perfect, appreciate it!

**Comment by Lagily** [comment]
Couldn't get your code to work, sadly I get the following error:

 Fatal error: Uncaught RiotAPI\LeagueAPI\Exceptions\RequestException: Summoner spell with given ID was not found.

**Comment by Lagily** [comment]
The id inside the MatchDto seems to be a number, there is no such thing in the JSON

**Comment by dolejska-daniel** [comment]
So I have pushed fixes to some related `DataDragonAPI` and `LeagueAPI` functions in `v3.0.9` (832d1855f55cce3b9b731ea61a872aeae8c742be). Make sure to pull these changes.

I have managed to display summoner spells with this snippet:
```php
// DataDragonAPI & LeagueAPI initialization
$summoner = $api->getSummonerByName('I am TheKronnY');

$matches = $api->getMatchlistByAccount($summoner->accountId);
$matchId = $matches->matches[0]->gameId;

$match = $api->getMatch($matchId);
foreach ($match->participants as $participant)
{
	$summoner_spell = $api->getStaticSummonerSpell($participant->spell1Id);
	echo DataDragonAPI::getSummonerSpellIconO($summoner_spell);

	$summoner_spell = $api->getStaticSummonerSpell($participant->spell2Id);
	echo DataDragonAPI::getSummonerSpellIconO($summoner_spell);

	echo "<br>";
}
```

**Comment by Lagily** [comment]
thanks, works now
