### ISSUE TITLE
Rate Limit

### ISSUE THREAD

**Issue by paranic** [dolejska-daniel/riot-api#47]
**Description**
Rate limit is not honored.

**To Reproduce**
1. set ```LeagueAPI::SET_CACHE_RATELIMIT => true``` as instructed by wiki
2. make some request
3. got some ServerLimitException with message "API call rate limit would be exceeded by this call."
4. then got some ServerLimitException with message "LeagueAPI: Rate limit for this API key was exceeded."

**Expected behavior**
who knows? maybe set limit exceed action.

**Comment by dolejska-daniel** [comment]
Hello @paranic, I've tested this myself, and what you are describing did not happen. Are you sure you are using latest version of this library? Please, if you have any more insights, feel free to comment.

**Comment by dolejska-daniel** [comment]
I'm closing this issue, since there has been no update.
