### ISSUE TITLE
createTournamentCodes_STUB returns BAD REQUEST, but seems to have everything

### ISSUE THREAD

**Issue by SlicewOw** [dolejska-daniel/riot-api#56]
**Describe the bug**
I created a homepage which is using your riot-api framework. As I created a cup within my CMS I created a tournamentId and a providerId. An object "TournamentCodeParameters" is created with related parameters. But the response is at any time: 

> LeagueAPI: Request is invalid. Bad request - The request entity had the following errors:[teamSize must be greater than or equal to 1 (was 0), spectatorType may not be null (was null), mapType may not be null (was null), pickType may not be null (was null)]

My TournamentCodeParameters object looks like:

```
RiotAPI\LeagueAPI\Objects\TournamentCodeParameters Object
(
    [spectatorType] => LOBBYONLY
    [teamSize] => 1
    [pickType] => TOURNAMENT_DRAFT
    [allowedSummonerIds] => 
    [mapType] => SUMMONERS_RIFT
    [metadata] => 
    [_data:protected] => Array
        (
            [spectatorType] => LOBBYONLY
            [teamSize] => 1
            [pickType] => TOURNAMENT_DRAFT
            [mapType] => SUMMONERS_RIFT
        )

    [_extension:protected] => 
)
```

**To Reproduce**
1. Try to create tournament codes with given providerId and tournamentId (stub only)

**Expected behavior**
I receive a list of codes when I am using the stub methods.

**Server (please complete the following information):**
 - PHP version: 7.2.11
 - MySQL version: 5.5.5-10.1.36-MariaDB
 - I am working on localhost with XAMPP

**Comment by dolejska-daniel** [comment]
There has been a problem with serialization of the `RiotAPI\LeagueAPI\Objects\TournamentCodeParameters` to JSON before sending it to the API, which then created an actual bad request.

I'm also very sorry it took me sooooo long to take a look at it.
