### ISSUE TITLE
RATE_LIMIT can use in multiprocessing?

### ISSUE THREAD

**Issue by 3masterplus** [dolejska-daniel/riot-api#59]
i use swoole multiprocessing work.

but i worry rate_limit error.. 

it's work ?

**Comment by dolejska-daniel** [comment]
Hello,
I haven't seen or used Swoole anywhere yet, so you will have to try it out yourself.

**Comment by 3masterplus** [comment]
@dolejska-daniel ok.. i try ... 

thank you.

**Comment by 3masterplus** [comment]
i try..

it's work 10 processing..

log is : API call rate limit would be exceeded by this call._data_
