### ISSUE TITLE
When iterable data is empty, is null.

### ISSUE THREAD

**Issue by santutu** [dolejska-daniel/riot-api#61]
Call match timeline in riot deleopment site 
![2](https://user-images.githubusercontent.com/28470293/66700061-7d1beb80-ed27-11e9-801e-3679c0253524.PNG)

Call match timeline by this library
![1](https://user-images.githubusercontent.com/28470293/66700062-7e4d1880-ed27-11e9-998a-c13dff1a219a.PNG)

not same result.

**Comment by dolejska-daniel** [comment]
Hello, could you provide me with platform and match ID?

**Comment by dolejska-daniel** [comment]
Never mind, your fix is correct!
