### ISSUE TITLE
Composer install error PHP7.2

### ISSUE THREAD

**Issue by juanBL** [dolejska-daniel/riot-api#63]
When I install the package it returns the following error:

` Problem 1
    - Conclusion: don't install dolejska-daniel/riot-api v4.0.2
    - Conclusion: don't install dolejska-daniel/riot-api v4.0.1
    - Conclusion: remove nette/utils v3.0.2
    - Installation request for dolejska-daniel/riot-api ^4.0 -> satisfiable by dolejska-daniel/riot-api[v4.0.0, v4.0.1, v4.0.2].
    - Conclusion: don't install nette/utils v3.0.2
    - dolejska-daniel/riot-api v4.0.0 requires nette/utils ^2.5 -> satisfiable by nette/utils[v2.5.0, v2.5.1, v2.5.2, v2.5.3].
    - Can only install one of: nette/utils[v2.5.0, v3.0.2].
    - Can only install one of: nette/utils[v2.5.1, v3.0.2].
    - Can only install one of: nette/utils[v2.5.2, v3.0.2].
    - Can only install one of: nette/utils[v2.5.3, v3.0.2].
    - Installation request for nette/utils (locked at v3.0.2) -> satisfiable by nette/utils[v3.0.2].
`
I am using php7.2, is it available?

**Comment by dolejska-daniel** [comment]
Hello, this doesn't seem like a PHP version related problem - your `composer.json` probably requests higher version of `nette/utils` than current version of this library allows. I will push some hotfix for `nette/utils` version, because I definitely can use higher version in this library.

**Comment by dolejska-daniel** [comment]
Could be fixed by `v4.0.3` - cd5116295d3bbc4c840de15d9fbd224629df7907.

**Comment by juanBL** [comment]
yes, it's working!

you are amazing! thank you for your quick response
