### ISSUE TITLE
Help With Async

### ISSUE THREAD

**Issue by Ntzzz** [dolejska-daniel/riot-api#67]
Hello , Im Trying to learn about async requests 
I've tried to follow your exemple but  I'm getting  only NULL results when using var_dump.
Here's the code 

![image](https://user-images.githubusercontent.com/59580452/71844993-244dbc00-30a6-11ea-86cf-da963d1d5f10.png)

Obs: I erased my api key to take the screenshot

Am I doing something Wrong ? What Should I "Echo" ?

**Comment by dolejska-daniel** [comment]
There really seems to be something wrong with it... I will check it out as soon as I can, but I currently don't have any spare time 😞.

**Comment by Ntzzz** [comment]
Ok Thanks for your reply!

**Comment by dolejska-daniel** [comment]
Hey @Ntzzz, good news - I've fixed the implementation of asynchronous requests. Turns out there has been an implementation error when resolving request promises.

Should be working on 53075a2d36f90b9021014e82a24e17c0ebb7bad9 :)
