### ISSUE TITLE
getRecentMatchlistByAccount - No longer a thing?

### ISSUE THREAD

**Issue by LewisLarsen** [dolejska-daniel/riot-api#69]
Hi there,

I'm attempting to pull my recent League matches but it appears that the method doesn't exist, I'm trying to do this - 

```$matches = $api->getRecentMatchlistByAccount($summoner->accountId)->matches;```

I can work around it no problem, I'm just curious as to why it isn't accepted anymore?

Using PHP version 7.2.24 and the latest version of the API wrapper.

**Comment by dolejska-daniel** [comment]
Hey, I think it got replaced by `getMatchlistByAccount` method a while ago.

**Comment by LewisLarsen** [comment]
Oh right, good to know - thanks!

Issue closed. :)
