### ISSUE TITLE
Usage with Laravel 

### ISSUE THREAD

**Issue by PaulJasiul** [dolejska-daniel/riot-api#7]
Hello, I am trying to use this API with my new Laravel 5.5 project and how to use this API without writting it in every page? I need to declare only region where I need it.

**Comment by dolejska-daniel** [comment]
Hello,

I am sorry, but I haven't played with Laravel yet, so I cannot really help you from my own experience. 😞 Try to find something for example on https://stackoverflow.com/.

**Comment by regiszanandrea** [comment]
Hi @PaulJasiul, you can use the app()->singleton on your AppServiceProvider class.

**Comment by dolejska-daniel** [comment]
Hello guys, if you're interested in usage of this library with Laravel, you can check out [this article](https://medium.com/@onezac/laravel-riotapi-part-1-80571c194d91) created by @zaclummys. Also, since it has been open long enough, and got some responses, I'm closing this issue.
