### ISSUE TITLE
Conflict with Laravel 7 dependencies

### ISSUE THREAD

**Issue by xKairu** [dolejska-daniel/riot-api#71]
**Describe the bug**
Installing `dolejska-daniel/riot-api` in a Laravel 7 project fails as L7 requires `symfony/console` 5.0

**To Reproduce**
1. Start a new Laravel 7 project
2. `composer install dolejska-daniel/riot-api`

**Expected behavior**
`dolejska-daniel/riot-api` should be installed. Not sure if it's as simple as bumping the version or adding it to support v4 and v5 side by side.

**Comment by dolejska-daniel** [comment]
Should be fixed on `master`. Feel free to try it!
