### ISSUE TITLE
How do you display reforged runes icons?

### ISSUE THREAD

**Issue by elreco** [dolejska-daniel/riot-api#74]
Hello :)

thank you for your wrapper!

I have an issue, how do you display the image path of the new runes ? 

When I retrieve a match, I get 6 perks variables (perk0, 1, 2 [...]) but I don't know how to display the icons from DataDragon API.

Can you help me please ? 

Thank you!

**Comment by dolejska-daniel** [comment]
Hello, thank you for the interest!

Currently there is no **easy** _easy_ way to do this, but there is _easy_ way:

**Source**
```php
// ...

$runes = $api->getStaticReforgedRunes()->runes;
$rune_paths = $api->getStaticReforgedRunePaths()->paths;

$match = $api->getMatch(...);
$player_stats = $match->participants[0]->stats;

// selected primary runes
DataDragonAPI::getReforgedRunePathIconO($rune_paths[$player_stats->perkPrimaryStyle]);
DataDragonAPI::getReforgedRuneIconO($reforged_runes[$player_stats->perk0]);
DataDragonAPI::getReforgedRuneIconO($reforged_runes[$player_stats->perk1]);
DataDragonAPI::getReforgedRuneIconO($reforged_runes[$player_stats->perk2]);
DataDragonAPI::getReforgedRuneIconO($reforged_runes[$player_stats->perk3]);

// selected secondary runes
DataDragonAPI::getReforgedRunePathIconO($rune_paths[$player_stats->perkSubStyle]);
DataDragonAPI::getReforgedRuneIconO($reforged_runes[$player_stats->perk4]);
DataDragonAPI::getReforgedRuneIconO($reforged_runes[$player_stats->perk5]);
```

**Render**
![Displayed Reforged Runes](https://i.ibb.co/WGRKmDf/image.png)

To be able to use StaticData endpoints you have to initialize DataDragon API - [more about that here](https://github.com/dolejska-daniel/riot-api/wiki/LeagueAPI%3A-StaticData-endpoints).

**Comment by elreco** [comment]
Nice! Thank you so much.

**Comment by dolejska-daniel** [comment]
Happy I could help! 😊 Feel free to ask in case you have any further questions :)
