### ISSUE TITLE
How to get champion ID by Name ?

### ISSUE THREAD

**Issue by elreco** [dolejska-daniel/riot-api#76]
Hello! 

Is there a way to get a champion ID with a given name?

Thank you!

**Comment by elreco** [comment]
I found a solution,

```php
$champions = DataDragonAPI::getStaticChampions();
  foreach($champions['data'] as $c){
    if(strcasecmp($c['name'], $champion) == 0){
     $champion = intval($c['key']);
  }
}
```

**Comment by dolejska-daniel** [comment]
Hello @elreco, I'm sorry for responding so late 😞 There are also dedicated functions in `DataDragonAPI` for finding champions by their keys/IDs (not their actual names, e.g.: `Annie`, `Wukong`, …, you have solved that correctly):
- For champion string names (e.g.: `Annie`, `MonkeyKing`, …) you can use `DataDragonAPI::getStaticChampionById($champion_name)` _(this isn't mistake, it really is `Id`.)_
- For champion integer IDs you can use `DataDragonAPI::getStaticChampionByKey($champion_id)` _(this isn't mistake, it really is `Key`.)_

Then you can easily access all their attributes - `name`, `key`, `id`, …
