### ISSUE TITLE
Possible package compatibility with Laravel

### ISSUE THREAD

**Issue by Nikla436** [dolejska-daniel/riot-api#77]
**Describe the bug**
While attempting to composer install, having many requirement compatibility issues with symphony/console ^5 from newest version of Laravel.

**Comment by dolejska-daniel** [comment]
Hello, thank you for your interest in this library!

You will have to be more specific, this doesn't tell me anything.. The library should be perfectly compatible with `symfony/console` version `v4` or `v5`.

Please copy-paste whole Composer output after `composer install`.

**Comment by dolejska-daniel** [comment]
#79 made me realize that no library version has been released with the fixes on master. Pull latest library version via Composer and this issue should be resolved. 😄
