### ISSUE TITLE
Third party code endpoint returns 404 not found.

### ISSUE THREAD

**Issue by exzib** [dolejska-daniel/riot-api#84]
Code to reproduce:

```
    public function getCode($region, $summoner_id) {
      $region_finder = new Region();
      $api = new LeagueAPI([
        LeagueAPI::SET_KEY    => $this->riotKey,
        //  Target region (you can change it during lifetime of the library instance)
        LeagueAPI::SET_REGION => $region_finder->getRegionName($region),
      ]);

      $code = $api->getThirdPartyCodeBySummonerId($summoner_id);

      dd($code);
    }
```

**Comment by dolejska-daniel** [comment]
That actually shouldn't be problem of the library itself, this endpoint is still proving to be unreliable and quite broken most of the time - even when client reports that third party code has been successfully saved, it is quite often impossible to retreive the code through the API.

Please check output at official [developer portal](https://developer.riotgames.com/apis#third-party-code-v4/GET_getThirdPartyCodeBySummonerId).

**Comment by dolejska-daniel** [comment]
I'm closing the issue since it has been inactive for a long time.
