### ISSUE TITLE
Question : Can we select more than one region for init.php ?

### ISSUE THREAD

**Issue by Lucasnl** [dolejska-daniel/riot-api#89]
For example 

`	LeagueAPI::SET_REGION => Region::BRASIL,Region::EUROPE_EAST, Region::EUROPE_WEST,
`

and if so , how does it work ?

**Comment by dolejska-daniel** [comment]
Hello, it is not possible, to set more than one region at the time, API needs to know exactly where to make the requests to. But what you can do is to switch active region with `$api->setRegion(Region::BRASIL)` or `$api->setTemporaryRegion(Region::BRASIL); $api->unsetTemporaryRegion();`.

If you've got any other questions, feel free to ask :)

**Comment by Lucasnl** [comment]
Thanks for the Help !!!
