### ISSUE TITLE
DataDragon API

### ISSUE THREAD

**Issue by Tiposbingo** [dolejska-daniel/riot-api#9]
Hi again,
is there any more info about DataDragon API ? implementation, maybe some example ? 

Thank you.

**Comment by dolejska-daniel** [comment]
Hello,

DataDragon implementation is currently not documented, so the only way to check how it works is to read function documentation comments [directly in file](https://github.com/dolejska-daniel/riot-api/blob/master/src/DataDragonAPI/DataDragonAPI.php).

I can briefly introduce it for you:
1. You need to initialize the library using one of these functions:
    - `DataDragonAPI::initByCdn()`, this will fetch latest version of DD from DD itself
    - `DataDragonAPI::initByRegion('eune')`, this will fetch latest version of DD from provided region (eune, euw, etc. -- make sure its lowercase)
    - `DataDragonAPI::initByVersion('8.1.1')`, this will explicitly specify requested version of DD, makes no request
    - `DataDragonAPI::initByApi($api)`, this function requires instance of `RiotAPI` and will request realm (region) object from API and use it to read current DD version
    - `DataDragonAPI::initByRealmObject($realm)`, this function accepts realm (region) object on its own, makes no request
2. You use static functions to get what you want!
    - `DataDragonAPI::getProfileIcon(50)`, this function returns instance of `Html` class, which on `__toString()` automatically renders itself as an <img> tag, with all the required attributes to display the image.

If you've got any further questions, feel free to ask 😺

**Comment by Tiposbingo** [comment]
Thank you very much 🥇

**Comment by Tiposbingo** [comment]
I find small issue. When you initalize the library using `DataDragonAPI::initByApi($api)` and then `DataDragonAPI::getProfileIcon(50)` 
return this link `http://ddragon.leagueoflegends.com/cdn8.1.1/img/profileicon/588.png` but you need **cdn/8.1.1**

**Comment by dolejska-daniel** [comment]
@Tiposbingo thanks! There was a bug, CDN link was not formed correctly when initialized by API or RealmObject. It should be fixed in cdd5e08.

**Comment by dolejska-daniel** [comment]
@Tiposbingo, I've updated DataDragonAPI's wiki pages, feel free to check them out 😸

**Comment by Tiposbingo** [comment]
@dolejska-daniel thanks, I'll test it with my laravel app soon
