### ISSUE TITLE
Using TFT api without needing to set League API Key

### ISSUE THREAD

**Issue by WildEgo** [dolejska-daniel/riot-api#92]
**Is your feature request related to a problem? Please describe.**
Not really, it's just an inconvenient to get an exception thrown cuz I didn't set a League API Key, even tho I'm only using TFT Endpoints.

**Describe the solution you'd like**
Just throw the exception if none of the 2 keys is present and if u access one without the key set for it.

**Describe alternatives you've considered**
It's ok to maintain the current behavior just think it's a QOL change.

**Comment by dolejska-daniel** [comment]
Hello! Thank you for your interest in this library!

This will be addressed in the upcomming large-scale rework I'm planning for the whole library. Please be patient ☺️

**Comment by WildEgo** [comment]
Thanks do not worry it's just a QOL change anyway, I don't mind adding an extra variable besides I only noticed it was a thing cuz I didn't look at the docs I just assumed!
