### ISSUE TITLE
PHP 8 Support

### ISSUE THREAD

**Issue by blood72** [dolejska-daniel/riot-api#93]
**Is your feature request related to a problem? Please describe.**
The PHP 8 has been released. 

**Describe the solution you'd like**
Is there any plan to support PHP 8?
I just want to check that you have a plan.
Then, I can wait for an upgrade until this is ready.

**Comment by dolejska-daniel** [comment]
Yes I surely want to support PHP8. I haven't looked into the incompatibilities just yet, will do soon!

**Comment by TheMY3** [comment]
@dolejska-daniel now only need to update dependencies in this repo? Base repository now v2.0.0 with 8.1 support

**Comment by dolejska-daniel** [comment]
> @dolejska-daniel now only need to update dependencies in this repo? Base repository now v2.0.0 with 8.1 support

https://github.com/dolejska-daniel/riot-api-league needs to be updated first. I am working on it though there are some issues with tests not going through.

**Comment by TheMY3** [comment]
@dolejska-daniel can not see error logs in https://github.com/dolejska-daniel/riot-api-league/pull/12 and can not help with it  :disappointed: waiting for fix, thanks for this)

**Comment by dolejska-daniel** [comment]
LeagueAPI v2 is now available: https://github.com/dolejska-daniel/riot-api-league/releases/tag/v2.0.0. I shall now update this metarepo with its latest version constraint. **_Nevertheless, this set of libraries desperately needs a new, at least partially skilled and interested maintainer to keep it going._** I find myself without time to spend towards this, and since I do not play the game anymore either, there is 0 motivation to do so in the small amount of free time I have.

**Comment by dolejska-daniel** [comment]
https://github.com/dolejska-daniel/riot-api/releases/tag/v5.0.0

**Comment by TheMY3** [comment]
> LeagueAPI v2 is now available: [dolejska-daniel/riot-api-league@`v2.0.0` (release)](https://github.com/dolejska-daniel/riot-api-league/releases/tag/v2.0.0). I shall now update this metarepo with its latest version constraint. **_Nevertheless, this set of libraries desperately needs a new, at least partially skilled and interested maintainer to keep it going._** I find myself without time to spend towards this, and since I do not play the game anymore either, there is 0 motivation to do so in the small amount of free time I have.

Thanks a lot, I have no free time too, but maybe I can help with it somethimes. I use this package for one project that used API for LoL, Valorant, TFT. So I interested at least in its support of current versions of PHP
