### ISSUE TITLE
getMatchlistByAccount with filters returning 404

### ISSUE THREAD

**Issue by MichaelZst** [dolejska-daniel/riot-api#98]
if I specify a champion in the function getMatchlistByAccount()  after a few data appear, I get  LeagueAPI: Not Found. Not found error

for example

```
 ....
      $apiEU = $this->api;


        $league = $apiEU->getLeagueEntriesExp("RANKED_SOLO_5x5", "CHALLENGER", "I");

        foreach ($league as  $sumId) {

          $account_id = $apiEU ->getSummoner($sumId->summonerId);
  
          print_r($api->getMatchlistByAccount($account_id->accountId,"420",NULL,"145");
}

```
![screenshot](https://user-images.githubusercontent.com/59580452/103963624-8701e980-5138-11eb-8f0c-932c13125262.jpg)

but if i do this
 
          print_r($api->getMatchlistByAccount($account_id->accountId,"420",NULL);

it works perfectly fine;

So is this a bug or am i  missing something ?

**Comment by dolejska-daniel** [comment]
Hello, I'd guess that if no matches satisfy the filter conditions, the API returns `404 Not Found`. Thought, you can validate this by getting the whole match list and filtering it yourself.

**Comment by MichaelZst** [comment]
I made a try catch and for now is working fine , thanks for the reply
